/**
 * RocChat — Channel E2E Sender Keys
 *
 * Each channel has a symmetric AES-256 key generated by an admin client at
 * channel creation. The key is wrapped (ECIES-style) per-subscriber using
 * their identity DH (X25519) public key:
 *
 *   1. Sender generates ephemeral X25519 keypair (E)
 *   2. ss = X25519_DH(E.priv, recipient.identityDH.pub)
 *   3. K = HKDF(ss, salt=channelId, info="rocchat-channel-key-wrap-v1", 32)
 *   4. envelope = AES-256-GCM(K, channelKey, iv=random(12))
 *   5. send (E.pub, ciphertext, iv, tag) to server
 *
 * Recipient unwraps:
 *   1. ss = X25519_DH(my.identityDH.priv, E.pub)
 *   2. K  = HKDF(ss, salt=channelId, info="rocchat-channel-key-wrap-v1", 32)
 *   3. channelKey = AES-256-GCM-Decrypt(K, ciphertext, iv, tag)
 *
 * The server only stores wrapped envelopes — it cannot recover any channel key.
 * Posts are then encrypted with the channel symmetric key + random per-message IV.
 */

import {
  generateX25519KeyPair,
  x25519DH,
  hkdf,
  aesGcmEncrypt,
  aesGcmDecrypt,
  randomBytes,
  toBase64,
  fromBase64,
  encode,
  decode,
} from '@rocchat/shared';
import { getSecretString, putSecretString } from './secure-store.js';
import { getIdentityDHKeyPair } from './session-manager.js';
import * as api from '../api.js';

const KEY_INFO = encode('rocchat-channel-key-wrap-v1');
const POST_INFO = encode('rocchat-channel-post-v1');

export interface ChannelKeyEnvelope {
  ephemeral_pub: string;
  ciphertext: string;
  iv: string;
  tag: string;
  key_version: number;
}

export interface RecipientInfo {
  user_id: string;
  identity_dh_key: string; // base64
  identity_key?: string;
}

// ── Local channel-key cache (encrypted at rest in IDB secure-store) ──

const LOCAL_KEY = (channelId: string, version: number) => `channel_key:${channelId}:v${version}`;

async function saveLocalChannelKey(channelId: string, version: number, key: Uint8Array): Promise<void> {
  await putSecretString(LOCAL_KEY(channelId, version), toBase64(key));
}

async function loadLocalChannelKey(channelId: string, version: number): Promise<Uint8Array | null> {
  const s = await getSecretString(LOCAL_KEY(channelId, version));
  return s ? fromBase64(s) : null;
}

// ── Wrap / unwrap (ECIES with X25519 + HKDF + AES-GCM) ──

async function deriveWrapKey(sharedSecret: Uint8Array, channelId: string): Promise<Uint8Array> {
  return hkdf(sharedSecret, encode(channelId), KEY_INFO, 32);
}

async function wrapForRecipient(
  channelKey: Uint8Array,
  channelId: string,
  recipientIdentityDHPub: Uint8Array,
): Promise<{ ephemeralPub: Uint8Array; ciphertext: Uint8Array; iv: Uint8Array; tag: Uint8Array }> {
  const ephemeral = await generateX25519KeyPair();
  const ss = await x25519DH(ephemeral.privateKey, recipientIdentityDHPub);
  const wrapKey = await deriveWrapKey(ss, channelId);
  const { ciphertext, iv, tag } = await aesGcmEncrypt(channelKey, wrapKey);
  return { ephemeralPub: ephemeral.publicKey, ciphertext, iv, tag };
}

async function unwrapEnvelope(
  envelope: ChannelKeyEnvelope,
  channelId: string,
): Promise<Uint8Array> {
  const myDH = await getIdentityDHKeyPair();
  const ephPub = fromBase64(envelope.ephemeral_pub);
  const ss = await x25519DH(myDH.privateKey, ephPub);
  const wrapKey = await deriveWrapKey(ss, channelId);
  return aesGcmDecrypt(
    fromBase64(envelope.ciphertext),
    wrapKey,
    fromBase64(envelope.iv),
    fromBase64(envelope.tag),
  );
}

// ── Public API: get/create/distribute channel keys ──

/**
 * Generate a fresh channel symmetric key, save locally, and immediately
 * upload a self-envelope so the same user can fetch it from another device.
 * Returns the new key.
 */
export async function generateAndUploadChannelKey(channelId: string): Promise<Uint8Array> {
  const channelKey = randomBytes(32);
  await saveLocalChannelKey(channelId, 1, channelKey);

  // Upload self-envelope so we can recover this key on other devices
  const myDH = await getIdentityDHKeyPair();
  const wrapped = await wrapForRecipient(channelKey, channelId, myDH.publicKey);
  const myUserId = localStorage.getItem('rocchat_user_id') || '';
  await api.req(`/channels/${channelId}/keys`, {
    method: 'POST',
    body: JSON.stringify({
      envelopes: [{
        recipient_id: myUserId,
        ephemeral_pub: toBase64(wrapped.ephemeralPub),
        ciphertext: toBase64(wrapped.ciphertext),
        iv: toBase64(wrapped.iv),
        tag: toBase64(wrapped.tag),
        key_version: 1,
      }],
    }),
  });
  return channelKey;
}

/**
 * Resolve the channel symmetric key — from local cache first, then by fetching
 * and unwrapping our envelope from the server. Returns null if no envelope is
 * available yet (subscriber must wait for an admin to distribute).
 */
export async function getChannelKey(channelId: string): Promise<Uint8Array | null> {
  // Try local cache (default version 1 for now)
  const local = await loadLocalChannelKey(channelId, 1);
  if (local) return local;

  // Fetch envelope from server
  try {
    const r = await api.req<{ envelope: ChannelKeyEnvelope | null }>(
      `/channels/${channelId}/keys/me`,
      { method: 'GET' }
    );
    if (!r.ok || !r.data?.envelope) return null;
    const envelope = r.data.envelope;
    const channelKey = await unwrapEnvelope(envelope, channelId);
    await saveLocalChannelKey(channelId, envelope.key_version || 1, channelKey);
    return channelKey;
  } catch {
    return null;
  }
}

/**
 * As an admin, distribute the channel key to subscribers who don't yet have
 * an envelope. Called when an admin opens a channel (best-effort, idempotent).
 */
export async function distributeChannelKeyToPending(channelId: string): Promise<number> {
  const channelKey = await loadLocalChannelKey(channelId, 1);
  if (!channelKey) return 0; // we don't hold the key — can't distribute

  let r: api.ApiResult<{ key_version: number; recipients: RecipientInfo[] }>;
  try {
    r = await api.req<{ key_version: number; recipients: RecipientInfo[] }>(
      `/channels/${channelId}/keys/pending`,
      { method: 'GET' }
    );
  } catch {
    return 0;
  }
  if (!r.ok || !r.data?.recipients?.length) return 0;

  const envelopes: Array<{
    recipient_id: string;
    ephemeral_pub: string;
    ciphertext: string;
    iv: string;
    tag: string;
    key_version: number;
  }> = [];

  for (const recipient of r.data.recipients) {
    if (!recipient.identity_dh_key) continue;
    try {
      const recipientPub = fromBase64(recipient.identity_dh_key);
      const wrapped = await wrapForRecipient(channelKey, channelId, recipientPub);
      envelopes.push({
        recipient_id: recipient.user_id,
        ephemeral_pub: toBase64(wrapped.ephemeralPub),
        ciphertext: toBase64(wrapped.ciphertext),
        iv: toBase64(wrapped.iv),
        tag: toBase64(wrapped.tag),
        key_version: r.data.key_version || 1,
      });
    } catch {
      /* skip recipient with malformed key */
    }
  }

  if (envelopes.length === 0) return 0;
  await api.req(`/channels/${channelId}/keys`, {
    method: 'POST',
    body: JSON.stringify({ envelopes }),
  });
  return envelopes.length;
}

// ── Post encrypt/decrypt ──

export interface EncryptedPost {
  ciphertext: string; // base64
  iv: string;         // base64
  tag: string;        // base64
  key_version: number;
}

/**
 * Encrypt a plaintext post body using the channel symmetric key.
 * Wire format: ratchet_header is JSON `{"v":N,"tag":"...","cv":1}` so subscribers
 * know which key version to use; ciphertext + iv are base64 fields.
 */
export async function encryptPost(channelId: string, plaintext: string): Promise<EncryptedPost> {
  const channelKey = await loadLocalChannelKey(channelId, 1);
  if (!channelKey) throw new Error('No channel key available');
  // Derive a per-channel post key so reused channelKey can't accidentally collide
  // with future contexts (forward-compat).
  const postKey = await hkdf(channelKey, encode(channelId), POST_INFO, 32);
  const { ciphertext, iv, tag } = await aesGcmEncrypt(encode(plaintext), postKey);
  return {
    ciphertext: toBase64(ciphertext),
    iv: toBase64(iv),
    tag: toBase64(tag),
    key_version: 1,
  };
}

/**
 * Decrypt a post. Returns null if no key available or auth fails (caller falls
 * back to legacy base64-plaintext rendering for backwards compatibility).
 */
export async function decryptPost(
  channelId: string,
  ciphertextB64: string,
  ivB64: string,
  tagB64: string,
  keyVersion: number = 1,
): Promise<string | null> {
  const channelKey = await loadLocalChannelKey(channelId, keyVersion);
  if (!channelKey) return null;
  try {
    const postKey = await hkdf(channelKey, encode(channelId), POST_INFO, 32);
    const plain = await aesGcmDecrypt(
      fromBase64(ciphertextB64),
      postKey,
      fromBase64(ivB64),
      fromBase64(tagB64),
    );
    return decode(plain);
  } catch {
    return null;
  }
}

/** Parse a `ratchet_header` field that may be E2E metadata or legacy. */
export function parsePostHeader(header: string | null | undefined): { v?: number; tag?: string; cv?: number } | null {
  if (!header) return null;
  try {
    const obj = JSON.parse(header);
    if (obj && typeof obj === 'object' && obj.cv === 1) return obj;
  } catch { /* not E2E */ }
  return null;
}
